jobs:
  Job1:
    name: Job 1
    steps:
      - type: script
        script-content: echo "Dev branch"
      - type: script
        script-content: touch output.txt
    files-publication:
      - path: touch.txt
        share-with-jobs: true
        publish-artifact: true
  Job2:
    name: Job 2
    dependencies:
      - Job1
    steps:
      - type: script
        script-content: error
  Job3:
    name: Job 3
    dependencies:
      - Job2:
          ignore-upstream-failures: true
